<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="3" total="7" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-24T14:23:55 CEST" name="Default suite" finished-at="2024-07-24T14:24:25 CEST" duration-ms="29967">
    <groups>
      <group name="regTest">
        <method signature="CreatContactTest.creatContactTest()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" name="creatContactTest" class="com.crm.contacts.CreatContactTest"/>
      </group> <!-- regTest -->
      <group name="smokeTest">
        <method signature="CreatContactTest.creatContactTest()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" name="creatContactTest" class="com.crm.contacts.CreatContactTest"/>
      </group> <!-- smokeTest -->
    </groups>
    <test started-at="2024-07-24T14:23:55 CEST" name="Default test" finished-at="2024-07-24T14:24:25 CEST" duration-ms="29967">
      <class name="com.crm.contacts.CreatContactTest">
        <test-method is-config="true" signature="connectDB()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:23:55 CEST" name="connectDB" finished-at="2024-07-24T14:23:55 CEST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectDB -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:23:55 CEST" name="launchBrowser" finished-at="2024-07-24T14:23:58 CEST" duration-ms="3365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="logintoApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:23:58 CEST" name="logintoApp" finished-at="2024-07-24T14:24:00 CEST" duration-ms="2054" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoApp -->
        <test-method retried="true" signature="creatContactTest()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:00 CEST" name="creatContactTest" finished-at="2024-07-24T14:24:05 CEST" duration-ms="4130" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.crm.contacts.CreatContactTest.creatContactTest(CreatContactTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatContactTest -->
        <test-method is-config="true" signature="logoutFromApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:05 CEST" name="logoutFromApp" finished-at="2024-07-24T14:24:06 CEST" duration-ms="1165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApp -->
        <test-method is-config="true" signature="logintoApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:06 CEST" name="logintoApp" finished-at="2024-07-24T14:24:07 CEST" duration-ms="1703" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoApp -->
        <test-method retried="true" signature="creatContactTest()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:07 CEST" name="creatContactTest" finished-at="2024-07-24T14:24:11 CEST" duration-ms="3435" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.crm.contacts.CreatContactTest.creatContactTest(CreatContactTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatContactTest -->
        <test-method is-config="true" signature="logoutFromApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:11 CEST" name="logoutFromApp" finished-at="2024-07-24T14:24:12 CEST" duration-ms="1028" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApp -->
        <test-method is-config="true" signature="logintoApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:12 CEST" name="logintoApp" finished-at="2024-07-24T14:24:14 CEST" duration-ms="1767" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoApp -->
        <test-method retried="true" signature="creatContactTest()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:14 CEST" name="creatContactTest" finished-at="2024-07-24T14:24:17 CEST" duration-ms="3504" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.crm.contacts.CreatContactTest.creatContactTest(CreatContactTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatContactTest -->
        <test-method is-config="true" signature="logoutFromApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:17 CEST" name="logoutFromApp" finished-at="2024-07-24T14:24:18 CEST" duration-ms="1004" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApp -->
        <test-method is-config="true" signature="logintoApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:18 CEST" name="logintoApp" finished-at="2024-07-24T14:24:20 CEST" duration-ms="1787" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoApp -->
        <test-method signature="creatContactTest()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:20 CEST" name="creatContactTest" finished-at="2024-07-24T14:24:24 CEST" duration-ms="3606" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.crm.contacts.CreatContactTest.creatContactTest(CreatContactTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatContactTest -->
        <test-method is-config="true" signature="logoutFromApp()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:24 CEST" name="logoutFromApp" finished-at="2024-07-24T14:24:25 CEST" duration-ms="964" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApp -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:25 CEST" name="closebrowser" finished-at="2024-07-24T14:24:25 CEST" duration-ms="373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="closeDB()[pri:0, instance:com.crm.contacts.CreatContactTest@43bc63a3]" started-at="2024-07-24T14:24:25 CEST" name="closeDB" finished-at="2024-07-24T14:24:25 CEST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDB -->
      </class> <!-- com.crm.contacts.CreatContactTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
